# Знакомство с библиотекой NumPy
---
NumPy — библиотека для работы с многомерными массивами и математических вычислений различного рода.  
NumPy можно рассматривать как некую альтернативу MATLAB.  
   
[Документация NumPy](https://numpy.org/doc/stable/reference/index.html)

**Импорт библиотеки NumPy:**

In [1]:
import numpy as np

**Создание одномерного массива:**

In [2]:
array_1D = np.array([1, 0])

**Вывод массива для ознакомления:**

In [3]:
array_1D

array([1, 0])

**Создание двумерного массива:**


In [4]:
array_2D = np.array([[1, 0, 2], [3, 4, 5], [6, 8, 7], [12, 22, 9]])
array_2D

array([[ 1,  0,  2],
       [ 3,  4,  5],
       [ 6,  8,  7],
       [12, 22,  9]])

**Просмотр типа данных элементов массива:**

In [5]:
array_2D.dtype

dtype('int64')

**Тип данных можно задать при создании массива:**

In [6]:
array_int32 = np.array([1], dtype = np.float)
print(array_int32.dtype, "- тип данных")
print(array_int32, "- значение переменных массива")

float64 - тип данных
[1.] - значение переменных массива


**Вывод размерности массива:**

In [7]:
print(array_1D.shape, "- количество элементов одномерного массива")
print(array_2D.shape, "- количество строк и столбцов двумерного массива")

(2,) - количество элементов одномерного массива
(4, 3) - количество строк и столбцов двумерного массива


**Варианты автоматического заполнения массивов:**

In [8]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.random((2, 4))

array([[3.31991291e-01, 1.11116170e-01, 5.70323999e-01, 6.71906540e-01],
       [2.65568518e-01, 3.90604223e-01, 1.40589389e-05, 3.67975452e-01]])

In [12]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Обращение к элементу массива по его индексу:**  
*(индексация начинается с нуля)*

In [14]:
print(array_1D)
array_1D[1]

[1 0]


0

In [15]:
print(array_2D)
array_2D[1, 2]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


5

In [16]:
print(array_2D[:, :])
array_2D[:2, :3]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[1, 0, 2],
       [3, 4, 5]])

**Просмотр элементов массива, удовлетворяющих условию:**

In [17]:
array_2D > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
array_2D[array_2D > 5]

array([ 6,  8,  7, 12, 22,  9])

**Изменение размерности матрицы:**

In [19]:
print(array_2D)
array_2D.flatten()

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([ 1,  0,  2,  3,  4,  5,  6,  8,  7, 12, 22,  9])

In [20]:
print(array_2D)
array_2D.reshape(6,2)

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0],
       [ 2,  3],
       [ 4,  5],
       [ 6,  8],
       [ 7, 12],
       [22,  9]])

In [21]:
#Метод resize() изменяет размерность массива и перезаписывает его
print(array_2D)
array_2D.resize(2, 6)
array_2D

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0,  2,  3,  4,  5],
       [ 6,  8,  7, 12, 22,  9]])

**Простые действия с массивами:**

In [22]:
a = np.array([1, 2])
b = np.array([2, 3])

In [23]:
#сложение
print(a + b, '\n')
print(np.add(a, b))

[3 5] 

[3 5]


In [24]:
#вычитание
print(a - b, '\n')
print(np.subtract(a, b))

[-1 -1] 

[-1 -1]


In [25]:
#деление
print(a / b, '\n')
print(np.divide(a, b))

[0.5        0.66666667] 

[0.5        0.66666667]


In [26]:
#поэлементное умножение
print(a * b, '\n')
print(np.multiply(a, b))

[2 6] 

[2 6]


**Скалярное произведение векторов, умножение матриц:**

In [27]:
a = np.array([2, 3])
b = np.array([[4], [5]])

In [28]:
print(np.dot(a, b), '\n')
print(a @ b)

[23] 

[23]


In [29]:
print(np.dot(a, 3), '\n')
print(a * 3)

[6 9] 

[6 9]


# Задачи для самостоятельного решения  
---

**1. Создать одномерный массив, заполненный двойками, но 6-ой элемент равен 8**

In [30]:
v = np.zeros([10])
v[6] = 8
v

array([0., 0., 0., 0., 0., 0., 8., 0., 0., 0.])

**2. Создать одномерный массив, со значениями от 15 до 98**

In [31]:
v = np.arange(start = 15, stop = 98)
v

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

**3. Перевернуть вектор  
*(123 -> 321)***

In [32]:
v = np.arange(start = 1, stop = 11)
v1 = v[: : -1]
print(v1)
 
v2 = np.flip(v, 0)
print(v2)

[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


**4. Найти минимальный и максимальный элемент двумерного массива размерностью 15х15**

In [33]:
m = np.random.random([15,15])
 
max_var1, max_var2 = m.min(), m.max()


min_var2 = np.min(m)
max_var2 = np.max(m)

**5. Поменять в двумерном массиве 3 и 4 строку между собой**

In [34]:
A = np.arange(25).reshape(5,5)
A[[2,3]] = A[[3,2]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [20 21 22 23 24]]


**6. Поменять каждый 4-ый элемент в одномерном массиве на заданное число: 212**

In [35]:
array = np.arange(100)
array[3: : 4] = 212
array

array([  0,   1,   2, 212,   4,   5,   6, 212,   8,   9,  10, 212,  12,
        13,  14, 212,  16,  17,  18, 212,  20,  21,  22, 212,  24,  25,
        26, 212,  28,  29,  30, 212,  32,  33,  34, 212,  36,  37,  38,
       212,  40,  41,  42, 212,  44,  45,  46, 212,  48,  49,  50, 212,
        52,  53,  54, 212,  56,  57,  58, 212,  60,  61,  62, 212,  64,
        65,  66, 212,  68,  69,  70, 212,  72,  73,  74, 212,  76,  77,
        78, 212,  80,  81,  82, 212,  84,  85,  86, 212,  88,  89,  90,
       212,  92,  93,  94, 212,  96,  97,  98, 212])

**7. Используя циклы написать собственную реализацию умножения двух двумерных матриц, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:**

In [36]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [37]:
%%time
C = A @ B

CPU times: user 13.7 ms, sys: 15.9 ms, total: 29.6 ms
Wall time: 48.1 ms


In [38]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 39.5 s, sys: 102 ms, total: 39.6 s
Wall time: 40.6 s
